train_config = {
    'input_height': 32,
    'input_width': 32,
    'num_channels': 3,
    'resnet_model_config': {
        'input_height': 32,
        'input_width': 32,
        'num_channels': 3,
        'num_classes': 10,
        'num_residual_units': [5, 5, 5],
        'num_filters': [16, 16, 32, 64],
        'strides': [1, 2, 2],
        'init_stride': 1,
        'init_max_pool': False,
        'init_filter_size': 3,
        'use_bottleneck': False,
        'build_classifier': True,
        'weight_decay': 2e-4,
        'data_format': "NCHW",
        'dropout': 0.0,
    },
    'optimizer_config': {
        'type': "momentum",
        'learn_rate': 1e-1,
        'momentum': 9e-1,
        'batch_size': 100,
        'max_train_iter': 80000,
        'learn_rate_decay_steps': [40000, 60000],
        'learn_rate_scheduler_type': "fixed",
        'learn_rate_list': [1e-2, 1e-3],
    },
    'seed': 1234,
}
